#!/bin/bash

set -efu

declare -r LC='{' RC='}' LP='(' RP=')' D='$' B='\' S=' ' Q="'" QQ='"'
declare -r B2=$B BB=$B$B BD=$B$D

# utility
concat() {
  local -n var_=$1
  local ifs=$IFS
  IFS=$DELIM
  echo "${var_[*]}"
  IFS=$ifs
}
split() {
  local src=$1 t=$DELIM
  local -n dst_=$2
  dst_=()
  while test "$src"; do
    if [[ "$src" == *$t* ]]; then
      dst_+=("${src%%$t*}")
      src=${src#*$t}
    else
      dst_+=("$src")
      src=
    fi
  done
}

# error handling
usage() {
  cat <<EOF >&2
USAGE: $0 [-v] [-d DELIM] PROGRAM [args ...]

    -v  debug mode
    -d  use DELIM instead of TAB for delimiter
EOF
  exit 1
}
error-eof() {
  cat <<EOF >&2
ERROR: no newline at end of file
EOF
  exit 1
}
error-halt() {
  cat <<EOF >&2
ERROR: no transition rule:
$(concat ARGS)
EOF
  exit 1
}
error-missing() {
  cat <<EOF >&2
ERROR: missing subst after match:
$msg
EOF
  exit 1
}
error-option() {
  cat <<EOF >&2
ERROR: unknown option: $msg
EOF
  usage
}
error-file() {
  cat <<EOF
ERROR: not found: $msg
EOF
  exit 1
}
error-eval() {
  cat <<EOF >&2
ERROR: outbound index in this subst:
$(concat SUBST_$INDEX)
EOF
  exit $1
}

# escape
escape-preprocess() {
  local -n opts_=$1
  opts_+=(-e s"/$LC/{LC}/"g)
  opts_+=(-e s"/$RC/{RC}/"g)
  opts_+=(-e s"/{LC${LC}RC}/{LC}/"g)
  opts_+=(-e s"/$LP/{LP}/"g)
  opts_+=(-e s"/$RP/{RP}/"g)
  opts_+=(-e s"/$BD/{D}/"g)
  opts_+=(-e s"/$BB/{B}/"g)
  opts_+=(-e s"/$S/{S}/"g)
  opts_+=(-e s"/$Q/{Q}/"g)
  opts_+=(-e s"/$QQ/{QQ}/"g)
}
escape-prepare-match() {
  local -n opts_=$1
  if test -z "${ESCAPE_MATCH_OPTS+set}"; then
    declare -ag ESCAPE_MATCH_OPTS
    escape-preprocess ESCAPE_MATCH_OPTS
    ESCAPE_MATCH_OPTS+=(-e s'/{B}{B}/{BB}/'g)
    ESCAPE_MATCH_OPTS+=(-e s"/{D}/{BD}/"g)
    ESCAPE_MATCH_OPTS+=(-e s"/{B}$D/{BB}/"g)
    declare -gr ESCAPE_MATCH_OPTS
  fi
  opts_=("${ESCAPE_MATCH_OPTS[@]}")
}
escape-prepare-subst() {
  local -n opts_=$1
  local var=$2
  if test -z "${ESCAPE_SUBST_OPTS+set}"; then
    declare -ag ESCAPE_SUBST_OPTS
    escape-preprocess ESCAPE_SUBST_OPTS
    ESCAPE_SUBST_OPTS+=(-e s'/{B}{B}/{B2}/'g)
    ESCAPE_SUBST_OPTS+=(-e s"/{B}{D}/{BD}/"g)
    ESCAPE_SUBST_OPTS+=(-e s"/{D}\([0-9]\)\([0-9]\)/{$var\1[\2]}/"g)
    ESCAPE_SUBST_OPTS+=(-e s"/{D}\([0-9]\)/{$var\1[0]}/"g)
    declare -gr ESCAPE_SUBST_OPTS
  fi
  opts_=("${ESCAPE_SUBST_OPTS[@]}")
}
escape() {
  local tmp
  local -n opts_=$1
  tmp=$(sed "${opts_[@]}" -e s"/\({[^{}]*}\)/$BD\1/"g)
  (eval echo "$tmp") || error-eval $?
}

# initialization
read-line() {
  local ifs=$IFS
  local -i err=0
  IFS=
  read -r line || err=$?
  IFS=$ifs
  return $err
}
parse-rules() {
  declare -ig COUNT=0
  declare -ag MATCH_RULES SUBST_RULES
  local line prev= msg
  local -i i
  for ((i=1; ; i++)); do
    if ! read-line; then
      test "$line" && error-eof
      test "$prev" && error-missing
      break
    elif test "$prev"; then
      test "$line" || error-missing
      MATCH_RULES[COUNT]=$prev
      SUBST_RULES[COUNT]=$line
      declare -ag MATCH_$COUNT SUBST_$COUNT
      split "$prev" MATCH_$COUNT
      split "$line" SUBST_$COUNT
      declare -gr MATCH_$COUNT SUBST_$COUNT
      ((COUNT++)) || :
      prev=
    elif test "$line"; then
      prev=$line
      msg="line:$i: $line"
    fi
  done
  declare -gr COUNT MATCH_RULES SUBST_RULES
}
init() {
  local msg
  declare -g DEBUG DELIM=$'\t'
  declare -ag ARGS
  (($#)) || usage
  while [[ "${1-}" == -* ]]; do
    msg=$1
    shift
    case "$msg" in
      -d) DELIM=$1; shift;;
      -h) usage;;
      -v) DEBUG=on;;
      -*) error-option;;
    esac
  done
  (($#)) || usage
  msg=$1
  test -f "$1" || error-file
  parse-rules <"$1"
  shift
  ARGS=('$' "$@")
}

# matching
pattern-match() {
  local -a opts
  local -n match_=MATCH_$INDEX
  local m
  set -- "${ARGS[@]}"
  escape-prepare-match opts
  for m in "${match_[@]}"; do
    (($#)) || return
    m=$(escape opts <<<"$m")
    [[ "$1" =~ ^$m$ ]] || return
    shift
  done
}
scan-match() {
  declare -ig INDEX
  for ((INDEX=0; INDEX<COUNT; INDEX++)); do
    pattern-match && return
  done
  return 1
}

# rewriting
rewrite-rematch() {
  local -n match_=MATCH_$INDEX
  local -a opts
  local -i i=0
  local match
  escape-prepare-match opts
  for match in "${match_[@]}"; do
    match=$(escape opts <<<"$match")
    [[ "${ARGS[i]}" =~ ^$match$ ]] || :
    local -n rematch_=rematch_$((i++))
    rematch_=("${BASH_REMATCH[@]}")
  done
}
rewrite-subst() {
  local -n subst_=SUBST_$INDEX
  local -a opts args
  local subst
  escape-prepare-subst opts rematch_
  args=()
  for subst in "${subst_[@]}"; do
    subst=$(escape opts <<<"$subst")
    args+=("$subst")
  done
  args+=("${ARGS[@]:count}")
  ARGS=("${args[@]}")
}
rewrite() {
  local -n match_=MATCH_$INDEX
  local -i i=0 count=${#match_[@]}
  for ((i=0; i<count; i++)); do
    local -a rematch_$i
  done
  rewrite-rematch
  rewrite-subst
}

# entry point
debug() {
  test "${DEBUG-}" && echo " -> $(concat ARGS)"
}
run() {
  while test "${ARGS[0]}"; do
    debug
    scan-match || error-halt
    rewrite
  done
  echo "${ARGS[@]:1}"
}

init "$@"
run
