#!/bin/bash

set -eu

RULES=()
ARGS=()
TMP=()

init() {
  local line
  RULES=()
  while read -r line; do
    RULES+=("$line")
  done <"$1"
  shift
  ARGS=("$@")
}
load-rule() {
  local ifs=$IFS
  set -f
  IFS=$'\t'
  TMP=(${RULES[$1]})
  IFS=$ifs
}

init "$@"
